title: "HYDRA: HYdrological Drought & Rainfall Atlas"
description: "Regression and visualization toolkit for teleconnections and drought analysis"
#theme: jekyll-theme-cayman
theme: none
markdown: kramdown